name: Test Strip

on:
  push:
    branches: [ master ]
 

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Grab libDDD artefacts
      run: wget --progress=dot:mega https://github.com/lip6/libDDD/raw/${{ runner.os }}/${{ runner.os }}.tgz ; tar xzf ${{ runner.os }}.tgz ;
    - name: test paths
      run: which strip ; ls -lah /usr/bin/strip
    - name: Install packages
      run: brew install gcc autoconf automake libtool binutils bison flex ;
    - name: test paths
      run: which strip ; ls -lah /usr/bin/strip ; ls -lah /usr/local/opt/
    - name: configure
      run: ./configure YACC='/usr/local/opt/bison/bin/bison -y' AR='gcc-ar-10' NM='gcc-nm-10' RANLIB='gcc-ranlib-10' CXX='g++-10' CC='gcc-10' --prefix=$PWD/usr/local/  --with-libexpat=$PWD/usr/local/ --with-libddd=$PWD/usr/local/ --with-gmp=$PWD/usr/local/ --with-antlrc=$PWD/usr/local/   --with-antlrjar=$PWD/usr/local/lib/antlr-3.4-complete.jar CPPFLAGS="-I$(pwd)/usr/local/include -DNDEBUG" LDFLAGS="-L$(pwd)/usr/local/lib" || cat config.log ; 
    - name: make 
      run: make -j 4
    - name: look
      run: ls -lah
    - name: strip
      run: strip tst1 ; ls -lah ; strip -S -x tst1 ; ls -lah      
      
